//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.02 at 06:17:52 PM CEST 
//


package org.perfcake.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.perfcake.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.perfcake.model
     * 
     */
    private ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScenarioModel }
     * 
     */
    public ScenarioModel createScenario() {
        return new ScenarioModel();
    }

    /**
     * Create an instance of {@link ScenarioModel.Validation }
     * 
     */
    public static ScenarioModel.Validation createValidation() {
        return new ScenarioModel.Validation();
    }

    /**
     * Create an instance of {@link ScenarioModel.Messages }
     * 
     */
    public static ScenarioModel.Messages createMessages() {
        return new ScenarioModel.Messages();
    }

    /**
     * Create an instance of {@link ScenarioModel.Messages.Message }
     * 
     */
    public static ScenarioModel.Messages.Message createMessage() {
        return new ScenarioModel.Messages.Message();
    }

    /**
     * Create an instance of {@link ScenarioModel.Reporting }
     * 
     */
    public static ScenarioModel.Reporting createReporting() {
        return new ScenarioModel.Reporting();
    }

    /**
     * Create an instance of {@link ScenarioModel.Reporting.Reporter }
     * 
     */
    public static ScenarioModel.Reporting.Reporter createReporter() {
        return new ScenarioModel.Reporting.Reporter();
    }

    /**
     * Create an instance of {@link ScenarioModel.Reporting.Reporter.Destination }
     * 
     */
    public static ScenarioModel.Reporting.Reporter.Destination createDestination() {
        return new ScenarioModel.Reporting.Reporter.Destination();
    }

    /**
     * Create an instance of {@link ScenarioModel.Generator }
     * 
     */
    public static ScenarioModel.Generator createGenerator() {
        return new ScenarioModel.Generator();
    }

    /**
     * Create an instance of {@link ScenarioModel.Properties }
     * 
     */
    public static ScenarioModel.Properties createProperties() {
        return new ScenarioModel.Properties();
    }

    /**
     * Create an instance of {@link ScenarioModel.Sender }
     * 
     */
    public static ScenarioModel.Sender createSender() {
        return new ScenarioModel.Sender();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public static Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public static Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link ScenarioModel.Validation.Validator }
     * 
     */
    public static ScenarioModel.Validation.Validator createValidator() {
        return new ScenarioModel.Validation.Validator();
    }

    /**
     * Create an instance of {@link ScenarioModel.Messages.Message.ValidatorRef }
     * 
     */
    public static ScenarioModel.Messages.Message.ValidatorRef createValidatorRef() {
        return new ScenarioModel.Messages.Message.ValidatorRef();
    }

    /**
     * Create an instance of {@link ScenarioModel.Reporting.Reporter.Destination.Period }
     * 
     */
    public static ScenarioModel.Reporting.Reporter.Destination.Period createPeriod() {
        return new ScenarioModel.Reporting.Reporter.Destination.Period();
    }

    /**
     * Create an instance of {@link ScenarioModel.Generator.Run }
     * 
     */
    public static ScenarioModel.Generator.Run createrRun() {
        return new ScenarioModel.Generator.Run();
    }

}
