//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.02 at 06:17:52 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:perfcake:scenario:0.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.perfcake.model;
