//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.02 at 06:17:52 PM CEST
//

package org.perfcake.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="generator">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="run">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="threads" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sender">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reporting" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;sequence>
 *                     &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;element name="reporter" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="destination" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="period" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="messages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="validatorRef" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element ref="{urn:perfcake:scenario:0.2}header" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="multiplicity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="validation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="validator" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "properties", "generator", "sender", "reporting", "messages", "validation" })
@XmlRootElement(name = "scenario")
public class ScenarioModel {

   protected ScenarioModel.Properties properties;
   @XmlElement(required = true)
   protected ScenarioModel.Generator generator;
   @XmlElement(required = true)
   protected ScenarioModel.Sender sender;
   protected ScenarioModel.Reporting reporting;
   protected ScenarioModel.Messages messages;
   protected ScenarioModel.Validation validation;
   @XmlAttribute(name = "enabled")
   protected Boolean enabled;

   /**
    * Gets the value of the properties property.
    * 
    * @return
    *         possible object is {@link ScenarioModel.Properties }
    * 
    */
   public ScenarioModel.Properties getProperties() {
      return properties;
   }

   /**
    * Sets the value of the properties property.
    * 
    * @param value
    *           allowed object is {@link ScenarioModel.Properties }
    * 
    */
   public ScenarioModel setProperties(ScenarioModel.Properties value) {
      this.properties = value;
      return this;
   }

   /**
    * Gets the value of the generator property.
    * 
    * @return
    *         possible object is {@link ScenarioModel.Generator }
    * 
    */
   public ScenarioModel.Generator getGenerator() {
      return generator;
   }

   /**
    * Sets the value of the generator property.
    * 
    * @param value
    *           allowed object is {@link ScenarioModel.Generator }
    * 
    */
   public ScenarioModel setGenerator(ScenarioModel.Generator value) {
      this.generator = value;
      return this;
   }

   /**
    * Gets the value of the sender property.
    * 
    * @return
    *         possible object is {@link ScenarioModel.Sender }
    * 
    */
   public ScenarioModel.Sender getSender() {
      return sender;
   }

   /**
    * Sets the value of the sender property.
    * 
    * @param value
    *           allowed object is {@link ScenarioModel.Sender }
    * 
    */
   public ScenarioModel setSender(ScenarioModel.Sender value) {
      this.sender = value;
      return this;
   }

   /**
    * Gets the value of the reporting property.
    * 
    * @return
    *         possible object is {@link ScenarioModel.Reporting }
    * 
    */
   public ScenarioModel.Reporting getReporting() {
      return reporting;
   }

   /**
    * Sets the value of the reporting property.
    * 
    * @param value
    *           allowed object is {@link ScenarioModel.Reporting }
    * 
    */
   public ScenarioModel setReporting(ScenarioModel.Reporting value) {
      this.reporting = value;
      return this;
   }

   /**
    * Gets the value of the messages property.
    * 
    * @return
    *         possible object is {@link ScenarioModel.Messages }
    * 
    */
   public ScenarioModel.Messages getMessages() {
      return messages;
   }

   /**
    * Sets the value of the messages property.
    * 
    * @param value
    *           allowed object is {@link ScenarioModel.Messages }
    * 
    */
   public ScenarioModel setMessages(ScenarioModel.Messages value) {
      this.messages = value;
      return this;
   }

   /**
    * Gets the value of the validation property.
    * 
    * @return
    *         possible object is {@link ScenarioModel.Validation }
    * 
    */
   public ScenarioModel.Validation getValidation() {
      return validation;
   }

   /**
    * Sets the value of the validation property.
    * 
    * @param value
    *           allowed object is {@link ScenarioModel.Validation }
    * 
    */
   public ScenarioModel setValidation(ScenarioModel.Validation value) {
      this.validation = value;
      return this;
   }

   /**
    * Gets the value of the enabled property.
    * 
    * @return
    *         possible object is {@link Boolean }
    * 
    */
   public Boolean isEnabled() {
      return enabled;
   }

   /**
    * Sets the value of the enabled property.
    * 
    * @param value
    *           allowed object is {@link Boolean }
    * 
    */
   public ScenarioModel setEnabled(Boolean value) {
      this.enabled = value;
      return this;
   }

   /**
    * <p>
    * Java class for anonymous complex type.
    * 
    * <p>
    * The following schema fragment specifies the expected content contained within this class.
    * 
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *         &lt;element name="run">
    *           &lt;complexType>
    *             &lt;complexContent>
    *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
    *               &lt;/restriction>
    *             &lt;/complexContent>
    *           &lt;/complexType>
    *         &lt;/element>
    *       &lt;/sequence>
    *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
    *       &lt;attribute name="threads" type="{http://www.w3.org/2001/XMLSchema}string" />
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    * 
    * 
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = { "properties", "run" })
   public static class Generator {

      @XmlElement(name = "property")
      protected List<Property> properties;
      @XmlElement(required = true)
      protected ScenarioModel.Generator.Run run;
      @XmlAttribute(name = "class")
      protected String clazz;
      @XmlAttribute(name = "threads")
      protected String threads;

      /**
       * Gets the value of the property property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getProperty().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link Property }
       * 
       * 
       */
      public List<Property> getProperties() {
         if (properties == null) {
            properties = new ArrayList<Property>();
         }
         return this.properties;
      }

      public Generator addProperty(Property p) {
         this.getProperties().add(p);
         return this;
      }
      
      /**
       * Gets the value of the run property.
       * 
       * @return
       *         possible object is {@link ScenarioModel.Generator.Run }
       * 
       */
      public ScenarioModel.Generator.Run getRun() {
         return run;
      }

      /**
       * Sets the value of the run property.
       * 
       * @param value
       *           allowed object is {@link ScenarioModel.Generator.Run }
       * 
       */
      public Generator setRun(ScenarioModel.Generator.Run value) {
         this.run = value;
         return this;
      }

      /**
       * Gets the value of the clazz property.
       * 
       * @return
       *         possible object is {@link String }
       * 
       */
      public String getClazz() {
         return clazz;
      }

      /**
       * Sets the value of the clazz property.
       * 
       * @param value
       *           allowed object is {@link String }
       * 
       */
      public Generator setClazz(String value) {
         this.clazz = value;
         return this;
      }

      /**
       * Gets the value of the threads property.
       * 
       * @return
       *         possible object is {@link String }
       * 
       */
      public String getThreads() {
         return threads;
      }

      /**
       * Sets the value of the threads property.
       * 
       * @param value
       *           allowed object is {@link String }
       * 
       */
      public Generator setThreads(String value) {
         this.threads = value;
         return this;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "")
      public static class Run {

         @XmlAttribute(name = "type")
         protected String type;
         @XmlAttribute(name = "value")
         protected String value;

         /**
          * Gets the value of the type property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getType() {
            return type;
         }

         /**
          * Sets the value of the type property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Run setType(String value) {
            this.type = value;
            return this;
         }

         /**
          * Gets the value of the value property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getValue() {
            return value;
         }

         /**
          * Sets the value of the value property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Run setValue(String value) {
            this.value = value;
            return this;
         }

      }

   }

   /**
    * <p>
    * Java class for anonymous complex type.
    * 
    * <p>
    * The following schema fragment specifies the expected content contained within this class.
    * 
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;element name="message" maxOccurs="unbounded">
    *           &lt;complexType>
    *             &lt;complexContent>
    *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *                 &lt;sequence>
    *                   &lt;element name="validatorRef" maxOccurs="unbounded" minOccurs="0">
    *                     &lt;complexType>
    *                       &lt;complexContent>
    *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                         &lt;/restriction>
    *                       &lt;/complexContent>
    *                     &lt;/complexType>
    *                   &lt;/element>
    *                   &lt;element ref="{urn:perfcake:scenario:0.2}header" maxOccurs="unbounded" minOccurs="0"/>
    *                   &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *                 &lt;/sequence>
    *                 &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                 &lt;attribute name="multiplicity" type="{http://www.w3.org/2001/XMLSchema}string" />
    *               &lt;/restriction>
    *             &lt;/complexContent>
    *           &lt;/complexType>
    *         &lt;/element>
    *       &lt;/sequence>
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    * 
    * 
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = { "messages" })
   public static class Messages {

      @XmlElement(required = true, name = "message")
      protected List<ScenarioModel.Messages.Message> messages;

      /**
       * Gets the value of the message property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the message property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getMessage().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link ScenarioModel.Messages.Message }
       * 
       * 
       */
      public List<ScenarioModel.Messages.Message> getMessages() {
         if (messages == null) {
            messages = new ArrayList<ScenarioModel.Messages.Message>();
         }
         return this.messages;
      }

      public Messages addMessage(Message m) {
         this.getMessages().add(m);
         return this;
      }
      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="validatorRef" maxOccurs="unbounded" minOccurs="0">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *         &lt;element ref="{urn:perfcake:scenario:0.2}header" maxOccurs="unbounded" minOccurs="0"/>
       *         &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
       *       &lt;/sequence>
       *       &lt;attribute name="uri" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="multiplicity" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "validatorRefs", "headers", "properties" })
      public static class Message {

         @XmlElement(name = "validatorRef")
         protected List<ScenarioModel.Messages.Message.ValidatorRef> validatorRefs;
         @XmlElement(name = "header")
         protected List<Header> headers;
         @XmlElement(name = "property")
         protected List<Property> properties;
         @XmlAttribute(name = "uri")
         protected String uri;
         @XmlAttribute(name = "multiplicity")
         protected String multiplicity;

         /**
          * Gets the value of the validatorRef property.
          * 
          * <p>
          * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the validatorRef property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * 
          * <pre>
          * getValidatorRef().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list {@link ScenarioModel.Messages.Message.ValidatorRef }
          * 
          * 
          */
         public List<ScenarioModel.Messages.Message.ValidatorRef> getValidatorRefs() {
            if (validatorRefs == null) {
               validatorRefs = new ArrayList<ScenarioModel.Messages.Message.ValidatorRef>();
            }
            return this.validatorRefs;
         }
         
         public Message addValidatorRef(ValidatorRef vr) {
            this.getValidatorRefs().add(vr);
            return this;
         }

         /**
          * Gets the value of the header property.
          * 
          * <p>
          * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the header property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * 
          * <pre>
          * getHeader().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list {@link Header }
          * 
          * 
          */
         public List<Header> getHeaders() {
            if (headers == null) {
               headers = new ArrayList<Header>();
            }
            return this.headers;
         }

         public Message addHeader(Header h) {
            this.getHeaders().add(h);
            return this;
         }
         /**
          * Gets the value of the property property.
          * 
          * <p>
          * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * 
          * <pre>
          * getProperty().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list {@link Property }
          * 
          * 
          */
         public List<Property> getProperties() {
            if (properties == null) {
               properties = new ArrayList<Property>();
            }
            return this.properties;
         }
         
         public Message addProperty(Property p) {
            this.getProperties().add(p);
            return this;
         }

         /**
          * Gets the value of the uri property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getUri() {
            return uri;
         }

         /**
          * Sets the value of the uri property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Message setUri(String value) {
            this.uri = value;
            return this;
         }

         /**
          * Gets the value of the multiplicity property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getMultiplicity() {
            return multiplicity;
         }

         /**
          * Sets the value of the multiplicity property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Message setMultiplicity(String value) {
            this.multiplicity = value;
            return this;
         }

         /**
          * <p>
          * Java class for anonymous complex type.
          * 
          * <p>
          * The following schema fragment specifies the expected content contained within this class.
          * 
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          * 
          * 
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "")
         public static class ValidatorRef {

            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *         possible object is {@link String }
             * 
             */
            public String getId() {
               return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *           allowed object is {@link String }
             * 
             */
            public ValidatorRef setId(String value) {
               this.id = value;
               return this;
            }

         }

      }

   }

   /**
    * <p>
    * Java class for anonymous complex type.
    * 
    * <p>
    * The following schema fragment specifies the expected content contained within this class.
    * 
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *       &lt;/sequence>
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    * 
    * 
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = { "properties" })
   public static class Properties {

      @XmlElement(name = "property")
      protected List<Property> properties;

      /**
       * Gets the value of the property property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getProperty().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link Property }
       * 
       * 
       */
      public List<Property> getProperties() {
         if (properties == null) {
            properties = new ArrayList<Property>();
         }
         return this.properties;
      }
      
      public Properties addProperty(Property p) {
         this.getProperties().add(p);
         return this;
      }

   }

   /**
    * <p>
    * Java class for anonymous complex type.
    * 
    * <p>
    * The following schema fragment specifies the expected content contained within this class.
    * 
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;sequence>
    *           &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *         &lt;/sequence>
    *         &lt;element name="reporter" maxOccurs="unbounded">
    *           &lt;complexType>
    *             &lt;complexContent>
    *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *                 &lt;sequence>
    *                   &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *                   &lt;element name="destination" maxOccurs="unbounded" minOccurs="0">
    *                     &lt;complexType>
    *                       &lt;complexContent>
    *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *                           &lt;sequence>
    *                             &lt;element name="period" maxOccurs="unbounded" minOccurs="0">
    *                               &lt;complexType>
    *                                 &lt;complexContent>
    *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                                   &lt;/restriction>
    *                                 &lt;/complexContent>
    *                               &lt;/complexType>
    *                             &lt;/element>
    *                             &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *                           &lt;/sequence>
    *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                         &lt;/restriction>
    *                       &lt;/complexContent>
    *                     &lt;/complexType>
    *                   &lt;/element>
    *                 &lt;/sequence>
    *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
    *               &lt;/restriction>
    *             &lt;/complexContent>
    *           &lt;/complexType>
    *         &lt;/element>
    *       &lt;/sequence>
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    * 
    * 
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = { "properties", "reporters" })
   public static class Reporting {

      @XmlElement(name = "property")
      protected List<Property> properties;
      @XmlElement(required = true, name="reporter")
      protected List<ScenarioModel.Reporting.Reporter> reporters;

      /**
       * Gets the value of the property property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getProperty().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link Property }
       * 
       * 
       */
      public List<Property> getProperties() {
         if (properties == null) {
            properties = new ArrayList<Property>();
         }
         return this.properties;
      }
      
      public Reporting addProperty(Property p) {
         this.getProperties().add(p);
         return this;
      }

      /**
       * Gets the value of the reporter property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the reporter property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getReporter().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link ScenarioModel.Reporting.Reporter }
       * 
       * 
       */
      public List<ScenarioModel.Reporting.Reporter> getReporters() {
         if (reporters == null) {
            reporters = new ArrayList<ScenarioModel.Reporting.Reporter>();
         }
         return this.reporters;
      }
      
      public Reporting addReporter(Reporter r) {
         this.getReporters().add(r);
         return this;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
       *         &lt;element name="destination" maxOccurs="unbounded" minOccurs="0">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="period" maxOccurs="unbounded" minOccurs="0">
       *                     &lt;complexType>
       *                       &lt;complexContent>
       *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                         &lt;/restriction>
       *                       &lt;/complexContent>
       *                     &lt;/complexType>
       *                   &lt;/element>
       *                   &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
       *                 &lt;/sequence>
       *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *       &lt;/sequence>
       *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "properties", "destinations" })
      public static class Reporter {

         @XmlElement(name = "property")
         protected List<Property> properties;
         @XmlElement(name = "destination")
         protected List<ScenarioModel.Reporting.Reporter.Destination> destinations;
         @XmlAttribute(name = "class")
         protected String clazz;

         /**
          * Gets the value of the property property.
          * 
          * <p>
          * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * 
          * <pre>
          * getProperty().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list {@link Property }
          * 
          * 
          */
         public List<Property> getProperties() {
            if (properties == null) {
               properties = new ArrayList<Property>();
            }
            return this.properties;
         }
         
         public Reporter addProperty(Property p) {
            this.getProperties().add(p);
            return this;
         }

         /**
          * Gets the value of the destination property.
          * 
          * <p>
          * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the destination property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * 
          * <pre>
          * getDestination().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list {@link ScenarioModel.Reporting.Reporter.Destination }
          * 
          * 
          */
         public List<ScenarioModel.Reporting.Reporter.Destination> getDestinations() {
            if (destinations == null) {
               destinations = new ArrayList<ScenarioModel.Reporting.Reporter.Destination>();
            }
            return this.destinations;
         }
         
         public Reporter addDestination(Destination d) {
            this.getDestinations().add(d);
            return this;
         }

         /**
          * Gets the value of the clazz property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getClazz() {
            return clazz;
         }

         /**
          * Sets the value of the clazz property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Reporter setClazz(String value) {
            this.clazz = value;
            return this;
         }

         /**
          * <p>
          * Java class for anonymous complex type.
          * 
          * <p>
          * The following schema fragment specifies the expected content contained within this class.
          * 
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;sequence>
          *         &lt;element name="period" maxOccurs="unbounded" minOccurs="0">
          *           &lt;complexType>
          *             &lt;complexContent>
          *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
          *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
          *               &lt;/restriction>
          *             &lt;/complexContent>
          *           &lt;/complexType>
          *         &lt;/element>
          *         &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
          *       &lt;/sequence>
          *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          * 
          * 
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = { "periods", "properties" })
         public static class Destination {

            @XmlElement(name = "period")
            protected List<ScenarioModel.Reporting.Reporter.Destination.Period> periods;
            @XmlElement(name = "property")
            protected List<Property> properties;
            @XmlAttribute(name = "class")
            protected String clazz;

            /**
             * Gets the value of the period property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the period property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getPeriod().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link ScenarioModel.Reporting.Reporter.Destination.Period }
             * 
             * 
             */
            public List<ScenarioModel.Reporting.Reporter.Destination.Period> getPeriods() {
               if (periods == null) {
                  periods = new ArrayList<ScenarioModel.Reporting.Reporter.Destination.Period>();
               }
               return this.periods;
            }
            
            public Destination addPeriod(Period p) {
               this.getPeriods().add(p);
               return this;
            }

            /**
             * Gets the value of the property property.
             * 
             * <p>
             * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * 
             * <pre>
             * getProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list {@link Property }
             * 
             * 
             */
            public List<Property> getProperties() {
               if (properties == null) {
                  properties = new ArrayList<Property>();
               }
               return this.properties;
            }

            public Destination addProperty(Property p) {
               this.getProperties().add(p);
               return this;
            }
            
            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *         possible object is {@link String }
             * 
             */
            public String getClazz() {
               return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *           allowed object is {@link String }
             * 
             */
            public Destination setClazz(String value) {
               this.clazz = value;
               return this;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * 
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Period {

               @XmlAttribute(name = "type")
               protected String type;
               @XmlAttribute(name = "value")
               protected String value;

               /**
                * Gets the value of the type property.
                * 
                * @return
                *         possible object is {@link String }
                * 
                */
               public String getType() {
                  return type;
               }

               /**
                * Sets the value of the type property.
                * 
                * @param value
                *           allowed object is {@link String }
                * 
                */
               public Period setType(String value) {
                  this.type = value;
                  return this;
               }

               /**
                * Gets the value of the value property.
                * 
                * @return
                *         possible object is {@link String }
                * 
                */
               public String getValue() {
                  return value;
               }

               /**
                * Sets the value of the value property.
                * 
                * @param value
                *           allowed object is {@link String }
                * 
                */
               public Period setValue(String value) {
                  this.value = value;
                  return this;
               }

            }

         }

      }

   }

   /**
    * <p>
    * Java class for anonymous complex type.
    * 
    * <p>
    * The following schema fragment specifies the expected content contained within this class.
    * 
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;element ref="{urn:perfcake:scenario:0.2}property" maxOccurs="unbounded" minOccurs="0"/>
    *       &lt;/sequence>
    *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    * 
    * 
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = { "properties" })
   public static class Sender {

      @XmlElement(name = "property")
      protected List<Property> properties;
      @XmlAttribute(name = "class")
      protected String clazz;

      /**
       * Gets the value of the property property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the property property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getProperty().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link Property }
       * 
       * 
       */
      public List<Property> getProperties() {
         if (properties == null) {
            properties = new ArrayList<Property>();
         }
         return this.properties;
      }

      public Sender addProperty(Property p) {
         this.getProperties().add(p);
         return this;
      }
      
      /**
       * Gets the value of the clazz property.
       * 
       * @return
       *         possible object is {@link String }
       * 
       */
      public String getClazz() {
         return clazz;
      }

      /**
       * Sets the value of the clazz property.
       * 
       * @param value
       *           allowed object is {@link String }
       * 
       */
      public Sender setClazz(String value) {
         this.clazz = value;
         return this;
      }

   }

   /**
    * <p>
    * Java class for anonymous complex type.
    * 
    * <p>
    * The following schema fragment specifies the expected content contained within this class.
    * 
    * <pre>
    * &lt;complexType>
    *   &lt;complexContent>
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
    *       &lt;sequence>
    *         &lt;element name="validator" maxOccurs="unbounded" minOccurs="0">
    *           &lt;complexType>
    *             &lt;simpleContent>
    *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
    *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
    *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
    *               &lt;/extension>
    *             &lt;/simpleContent>
    *           &lt;/complexType>
    *         &lt;/element>
    *       &lt;/sequence>
    *     &lt;/restriction>
    *   &lt;/complexContent>
    * &lt;/complexType>
    * </pre>
    * 
    * 
    */
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = { "validators" })
   public static class Validation {

      @XmlElement(name = "validator")
      protected List<ScenarioModel.Validation.Validator> validators;

      /**
       * Gets the value of the validator property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the validator property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getValidator().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list {@link ScenarioModel.Validation.Validator }
       * 
       * 
       */
      public List<ScenarioModel.Validation.Validator> getValidators() {
         if (validators == null) {
            validators = new ArrayList<ScenarioModel.Validation.Validator>();
         }
         return this.validators;
      }
      
      public Validation addValidator(Validator v) {
         this.getValidators().add(v);
         return this;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;simpleContent>
       *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
       *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/extension>
       *   &lt;/simpleContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "value" })
      public static class Validator {

         @XmlValue
         protected String value;
         @XmlAttribute(name = "id")
         protected String id;
         @XmlAttribute(name = "class")
         protected String clazz;

         /**
          * Gets the value of the value property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getValue() {
            return value;
         }

         /**
          * Sets the value of the value property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Validator setValue(String value) {
            this.value = value;
            return this;
         }

         /**
          * Gets the value of the id property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getId() {
            return id;
         }

         /**
          * Sets the value of the id property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Validator setId(String value) {
            this.id = value;
            return this;
         }

         /**
          * Gets the value of the clazz property.
          * 
          * @return
          *         possible object is {@link String }
          * 
          */
         public String getClazz() {
            return clazz;
         }

         /**
          * Sets the value of the clazz property.
          * 
          * @param value
          *           allowed object is {@link String }
          * 
          */
         public Validator setClazz(String value) {
            this.clazz = value;
            return this;
         }

      }

   }

}
